name: Update Breaking News

on:
  schedule:
    - cron: "*/15 * * * *"  # מריץ כל 15 דקות
  workflow_dispatch:  # מאפשר להריץ ידנית

jobs:
  update-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch breaking news
        run: |
          curl -s "https://newsapi.org/v2/top-headlines?sources=walla&apiKey=YOUR_NEWS_API_KEY" > breaking-news.json

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add breaking-news.json
          git commit -m "Updated breaking news" || echo "No changes to commit"
          git push
